### DISCUSSION TITLE
KVM + VXLAN

### DISCUSSION THREAD

**Discussion by UAnton** [apache/cloudstack#10449] [Q&A]
Hi,
I need help with KVM and vxlan.
I have 3 nodes with network config:
```
network:
  version: 2
  renderer: networkd

  ethernets:
    enp24s0f0np0:
      dhcp4: false
      dhcp6: false
      mtu: 9014
    enp24s0f1np1:
      dhcp4: false
      dhcp6: false
      mtu: 9014
    enp94s0f0np0:
      dhcp4: false
      dhcp6: false
      mtu: 9014
    enp94s0f1np1:
      dhcp4: false
      dhcp6: false
      mtu: 9014

  bonds:
    bond0:
      interfaces:
        - enp24s0f0np0
        - enp24s0f1np1
      parameters:
        mode: 802.3ad
        lacp-rate: fast
        mii-monitor-interval: 100
        transmit-hash-policy: layer3+4
      mtu: 9014

  vlans:
    vlan26:
      id: 26
      link: enp94s0f0np0
      addresses:
        - 172.16.26.91/24
      mtu: 9014
    vlan27:
      id: 27
      link: enp94s0f1np1
      addresses:
        - 172.16.27.91/24
      mtu: 9014
    vlan101:
      id: 101
      link: bond0
      mtu: 9014

  bridges:
    cloudbr0:
      interfaces:
        - bond0
      addresses:
        - 172.16.10.91/24
      routes:
        - to: 0.0.0.0/0
          via: 172.16.10.254
      nameservers:
        addresses:
          - 1.1.1.1
          - 8.8.8.8
      parameters:
        stp: false
        forward-delay: 0
      mtu: 9014

    cloudbr1:
      interfaces:
        - vlan101
      parameters:
        stp: false
        forward-delay: 0
      mtu: 9014
```
cloudbr0 - mgmt + public
cloudbr1 - guest

I have created two VMs and one isolated network. If each VM is on one node, everything is okay, but if one VM is on the other node, the network on this VM stops working.
What am I doing wrong? 
Thanks for your help!

P.S. ACS - 4.20, KVM nodes - Ubuntu 24.04. Switch - Mellanox MLX6036.
