### DISCUSSION TITLE
Setup Cloudstack HCI

### DISCUSSION THREAD

**Discussion by mpbraj** [apache/cloudstack#9363] [Q&A] [answered]
HI, Planning a test platform for installing and configuring CloudStack with 3 node KVM + storage cluster which is a HCI architecture....Also with  separate storage NIC...Can someone help me with some document/Howto or some website link where I can follow...
Thanks in Advance...
Raj...

**Comment by rajujith** [comment]
@mpbraj  I am not sure whether there is a document specific to HCI but you can achieve the same following the general installation guide: https://docs.cloudstack.apache.org/en/latest/installguide/index.html

**Comment by mpbraj** [comment]
I have gone through the doc, had configured a basic networking... The networking under cloudstack is so confusing ....if anyone possible to help me with how the HCI architecture physical connectivity is going to be..if the storage is separate NIC...

**Comment by yadvr** [comment, marked as answer]
@mpbraj my CloudStack homelab is a HCI setup with three Ubuntu 22.04 KVM hosts that are also used as storage & mgmt nodes, running on Intel NUC9 which has 1G nic used for guest/public network & 10G nic (pcie) used for mgmt/storage traffic:

<img width="1596" alt="Screenshot 2024-07-10 at 5 10 25 PM" src="https://github.com/apache/cloudstack/assets/95203/27ef4ad5-429f-49e6-87ec-03a22ea76b12">

Each of my hosts have 2 additional NVMes that are used as Ceph OSDs & the 3 nodes run Ceph mons etc. One of the node is used to run mgmt server & NFS secondary storage. I mainly use local storage (nvme) & Ceph in my HCI setup. Here's the cloudbr1 (10G) in my setup:

<img width="1474" alt="Screenshot 2024-07-10 at 5 10 37 PM" src="https://github.com/apache/cloudstack/assets/95203/cc734fa0-44f2-4422-a717-fcf325aa877f">

My notes are here https://rohityadav.cloud/blog/ceph/ and https://rohityadav.cloud/blog/cloudstack-kvm/

To accomplish this, all I had to do was create two bridges on each of my KVM hosts (cloudbr0 & cloudbr1), here's my netplan config for reference:

```
root@cms1:/home/rohit# cat /etc/netplan/00-installer-config.yaml
network:
  version: 2
  renderer: networkd
  ethernets:
    eno1:
      dhcp4: false
      dhcp6: false
      optional: true
    en112s0:
      dhcp4: false
      dhcp6: false
      optional: true
    eth0:
      dhcp4: false
      dhcp6: false
      optional: true
      match:
        macaddress: 14:02:xxxx
      set-name: eth0
      mtu: 9000
    enp1s0f1:
      dhcp4: false
      dhcp6: false
      optional: true
      match:
        macaddress: 14:02:xxx
      set-name: enp1s0f1
      mtu: 9000
  bridges:
    cloudbr0:
      addresses: [192.168.1.10/24]
      routes:
       - to: default
         via: 192.168.1.1
      nameservers:
        addresses: [192.168.1.1]
      interfaces: [eno1, en112s0]
      dhcp4: false
      dhcp6: false
      parameters:
        stp: false
        forward-delay: 0
    cloudbr1:
      addresses: [10.10.1.10/24]
      interfaces: [eth0, enp1s0f1]
      dhcp4: false
      dhcp6: false
      mtu: 9000
      parameters:
        stp: false
        forward-delay: 0
```

For VLAN/switching I use TP-Link Jetstream 8 Port Gigabit Smart Managed Switch which has the 1G nics of my hosts connected to it. For 10G nics, I just connected those nics on the hosts directly (i.e. I don't use a 10G switch as they are expensive) & the 10G network therefore are not routable to Internet (or my home network). When creating VLANs in the zone, i.e. for use in isolated network & VPC, I had to configure the switch for such VLANs: (my adv zone has only 6 vlans, as I mostly use shared network)

<img width="665" alt="Screenshot 2024-07-10 at 5 26 50 PM" src="https://github.com/apache/cloudstack/assets/95203/bd9f0b85-6d48-4925-ac83-d80d62b9c5df">

To implement the infra/networks, I use pfsense at home which implements the network firewall/routing on these VLANs:

<img width="566" alt="Screenshot 2024-07-10 at 5 27 23 PM" src="https://github.com/apache/cloudstack/assets/95203/791ba395-0cbc-441a-94c6-c1fbb8925b4a">

Here's the overall topology of my setup, which is a bit outdated but gives you an overall idea:

![Lab drawio copy](https://github.com/apache/cloudstack/assets/95203/1a148ed4-b4ac-4908-ae12-8cec8b5a816a)
