### DISCUSSION TITLE
Traefik return 404 page not found - Kubernetes on Cloudstack 4.17.2.0

### DISCUSSION THREAD

**Discussion by tuanhoangth1603** [apache/cloudstack#9906] [Q&A] [answered]
Hello,
I created a Kubernetes cluster on Cloudstack and used this guide (https://docs.cloudstack.apache.org/en/latest/plugins/cloudstack-kubernetes-provider.html) to deploy Traefik as an ingress controller. 
1. According to the guide:
_On successfully deploying the yaml file, a new Public IP Address in the same network as the cluster will be created. It will automatically have the firewall and port forwarding rules configured to distribute any traffic **amongst the cluster worker nodes**_

However, upon inspecting the LB rules, I noticed that the **control node** was also added as a backend server ?
![image](https://github.com/apache/cloudstack/assets/38004836/c6668261-d0ab-44e8-bf30-aa077c306897)

2. Furthermore, I created and deployed a file that defines a basic deployment, service, and ingress. However, when I curl http://k8s.lab.com.vn/, the response is "404 page not found". Is there a mistake in my YAML file? 
Thanks for your help!

```
---
apiVersion: v1
kind: Service
metadata:
  name: app
spec:
  selector:
    app: app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-deployment
  labels:
    app: app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
      - name: app
        image: nginx:latest
        ports:
        - containerPort: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: traefik-app-ingress
spec:
  rules:
    - host: k8s.lab.com.vn
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name:  app
                port:
                  number: 80
```
