### ISSUE TITLE
Add pre-commit hook `shellcheck-py` to standardize shell files

### ISSUE THREAD

**Issue by jbampton** [apache/cloudstack#10976]
https://github.com/shellcheck-py/shellcheck-py

https://www.shellcheck.net/

https://github.com/koalaman/shellcheck

Example `.pre-commit-config.yaml` entry:

```
 - repo: https://github.com/shellcheck-py/shellcheck-py
   rev: v0.10.0.1
   hooks:
     - id: shellcheck
```

Example `.shellcheckrc` config file:

```
disable=SC2004,SC2041,SC2155,SC2181
```
