### ISSUE TITLE
Network issue with VM running on second host.

### ISSUE THREAD

**Issue by Atiqul-Islam** [apache/cloudstack#7364]
##### ISSUE TYPE
 * Bug Report

##### COMPONENT NAME

~~~
VPN on newly added hosts.
~~~

##### CLOUDSTACK VERSION

~~~
4.17.1
~~~

##### SUMMARY
I have a Zone on Cloud Stack with network configuration specified above. I also have an isolated network (10.8.0.0/16) on the Zone. I also have a VM running on Zone connected to the isolated network, via a virtual router running on Host 1. 

I added a second host to the Zone as well. 
However, VMs connected to the same network running on the second host cannot cannot access the internet. 
VMs on the first host does have internet access and works as expected.

##### STEPS TO REPRODUCE

- Fresh Install of Apche CloudStack 4.17.1 on ubuntu 20.04 server 
- Network configuration on ubuntu server - ([bridge0 -> 10.4.0.0/16] & [bridge1 -> 10.6.0.0/16])
- Advance Zone with two Physical Network - ([Network 1 -> VLAN -> Management] & [Network 2 -> GRE -> Guest and Public])
- Isolated Network in Zone 1 - 10.8.0.0/16
- VM1 - Isolated Network 1 - Host 1
- VM2 - Isolated Network  2 - Host 2

Note: Management Server and Host 1 is running on Device A
          Host 2 is running on Device B
          
Device A network configuration
```
network:
  version: 2
  renderer: networkd
  ethernets:
       enp107s0:
          dhcp4: false
       enp108s0:
          dhcp4: false
  bridges:
      cloudbr0:
          addresses: [10.4.1.10/16]
          routes:
          - to: 0.0.0.0/0
            via: 10.4.1.1
            metric: 100
          nameservers:
                 addresses: [10.4.1.1]
          interfaces: [enp107s0]
          dhcp4: false
          dhcp6: false
      cloudbr1:
          addresses:  [10.6.1.10/16]
          routes:
          - to: 0.0.0.0/0
            via: 10.6.1.1
            metric: 1000
          nameservers:
                  addresses: [10.4.1.1]
          interfaces: [enp108s0]
          dhcp4: false
          dhcp6: false
```

Device B network configuration
```
network:
  version: 2
  renderer: networkd
  ethernets:
       enp107s0:
          dhcp4: false
       enp108s0:
          dhcp4: false
  bridges:
      cloudbr0:
          addresses: [10.4.1.11/16]
          routes:
          - to: 0.0.0.0/0
            via: 10.4.1.1
            metric: 100
          nameservers:
                 addresses: [10.4.1.1]
          interfaces: [enp107s0]
          dhcp4: false
          dhcp6: false
      cloudbr1:
          addresses:  [10.6.1.11/16]
          routes:
          - to: 0.0.0.0/0
            via: 10.6.1.1
            metric: 1000
          nameservers:
                  addresses: [10.4.1.1]
          interfaces: [enp108s0]
          dhcp4: false
          dhcp6: false
```

##### EXPECTED RESULTS

~~~
Both VM1 and VM2 should have internet connectivity. 
~~~

##### ACTUAL RESULTS

~~~
VM1 has internet connectivity, however VM2 does not.
~~~
