### ISSUE TITLE
new Kubernetes cluster goes into an error state

### ISSUE THREAD

**Issue by Stanley2911** [apache/cloudstack#7734]
##### ISSUE TYPE

 * Bug Report

##### COMPONENT NAME

Kubernetes

##### CONFIGURATION
KVM on Rocky Linux 8.7

##### SUMMARY
Whenever I am provisioning a new Kubernetes cluster, the cluster goes into an error state. The error obtained on GUI is given below

Error
Failed to setup Kubernetes cluster : k8s as it does not have desired number of nodes in ready state

Upon further inspection, the cluster has both controller & worker nodes in running state.

![image](https://github.com/apache/cloudstack/assets/134476960/8d949ea8-736b-478a-848f-603049373b3c)

**Comment by kiranchavala** [comment]
@Stanley2911 what is the kubernetes version you are trying to launch ?

**Comment by Stanley2911** [comment]
v1.23, v.1.25, v 1.26, I am getting same error on all versions

Sent from Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by rohityadavcloud** [comment]
@Stanley2911 thanks for reporting the issue, do you have overprovisioned RAM in your env? Can you try 1.26.6 or 1.27.3 isos from https://download.cloudstack.org/cks/ ?

**Comment by Stanley2911** [comment]
Hi Rohit,

Thanks a lot for your replies. I ll try to add v1.26.6 & 1.27.3 as well and get back to you.

**Comment by Stanley2911** [comment]
Hi Rohit,
 
Tried with both ISOs v1.26.6 & v1.27.3 as well. I am getting the same error. Screenshots are shared for your reference

![Screenshot 2023-07-11 134913](https://github.com/apache/cloudstack/assets/134476960/60ae7bb9-cdbb-4393-a732-b3a8dd813e21)
![Screenshot 2023-07-11 131615](https://github.com/apache/cloudstack/assets/134476960/9d1b84ca-a16c-409b-8f8d-e030fa90eaef)
![Screenshot 2023-07-11 140238](https://github.com/apache/cloudstack/assets/134476960/3b7d5af1-c96d-43e3-9b5e-c474ef014a64)
![Screenshot 2023-07-11 154226](https://github.com/apache/cloudstack/assets/134476960/8e2915d2-f0fe-4024-bfc7-39f4713548a1)
![Screenshot 2023-07-11 154448](https://github.com/apache/cloudstack/assets/134476960/bab5c4c1-3739-46ed-b149-c19905a1be94)

**Comment by kiranchavala** [comment]
@Stanley2911 what type of network are you using "stank8s2network" is it isolated network or a shared network ?

**Comment by Stanley2911** [comment]
Hello Kiranchavala, 

Thanks a lot for your response.
The stank8s2network is provisioned as an Isolated network. The screenshot is attached below

![image](https://github.com/apache/cloudstack/assets/134476960/d8525a17-6353-4c9f-b0db-17516cb7c80a)

**Comment by kiranchavala** [comment]
@Stanley2911 

1. Can you check if you are able to telnet to public IP of the CKS cluster on port 2222 , 6443.

You can get the publc ip address from the UI ( screenshots attached) 

![Screenshot 2023-07-12 at 10 47 35 AM](https://github.com/apache/cloudstack/assets/1401014/08e423f1-c3d9-446b-8131-7f48f070dcb5)

![Screenshot 2023-07-12 at 10 47 49 AM](https://github.com/apache/cloudstack/assets/1401014/a8c8ffc2-c53f-44aa-ad09-f2f27678d883)


2. Can you try to ssh into the controller node and worker node ( using the ssh key) 

Master node
ssh -i <ssh-private.key > -p 2222 cloud@Public ip address of Virtual Router

worker node
ssh -i <ssh-private.key > -p 2223 cloud@Public ip address of Virtual Router

![Screenshot 2023-07-12 at 10 48 05 AM](https://github.com/apache/cloudstack/assets/1401014/31f12fa3-2040-405e-8501-91c719044ef2)


3. Once you are able to ssh into the control node and worker node


Please check the /var/log/daemon.log

**Comment by Stanley2911** [comment]
I ll check & logs & get back to you.
Thanks

Sent from Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by Stanley2911** [comment]
Hi kiranchavala,


I have uploaded the both controller & worker node log files.
Please let me know what can be the issue.

[cloud@stank8s2-control-1894435c37b ~.txt](https://github.com/apache/cloudstack/files/12035417/cloud%40stank8s2-control-1894435c37b.txt)

[worker.txt](https://github.com/apache/cloudstack/files/12035428/worker.txt)

**Comment by Stanley2911** [comment]
Hi Kiranchavala,

Thanks for your help.
Apologies. The previously uploaded worker node file is empty.
The worker node log file is given below

[worker_node.txt](https://github.com/apache/cloudstack/files/12035471/worker_node.txt)

**Comment by kiranchavala** [comment]
@Stanley2911 could you please check if there are older daemon logs

From the worker node, i need the logs for the date  jul 11  as the maste node logs shows the same date

**Comment by Stanley2911** [comment]
@kiranchavala 

Thanks.
I ll collect the required logs & get back to you.

**Comment by Stanley2911** [comment]
@kiranchavala 

The requested file is attached.

Thank you

[controllernode01.txt](https://github.com/apache/cloudstack/files/12046401/controllernode01.txt)

**Comment by kiranchavala** [comment]
@Stanley2911 

Looks like the Kubernetes cluster is up and running, and the pods are all up 

Please check the node status also 

kubectl  get nodes

If the node status are in  ready status then you can update the database
 
example 

```
root@t2-control-1894e40b616:/home/cloud# kubectl get nodes
NAME                     STATUS   ROLES           AGE   VERSION
t2-control-1894e40b616   Ready    control-plane   22h   v1.27.3
t2-node-1894e40ebd8      Ready    <none>          22h   v1.27.3
```



mysql> use cloud;

Replace the name of the cluster
mysql>update  kubernetes_cluster set state="Running" where name=<>

**Comment by Stanley2911** [comment]
@kiranchavala 

Thanks.
I ll check and back to you.

**Comment by Stanley2911** [comment]
@kiranchavala 

Thanks.
I can see the cluster is now in a running state. But when I tried logging into the dashboard, I have to have a security token to login. But when i check running the following command
kubectl  -n kube-system get secret

I can see one service running. But when I am checking the same in the Kubernetes cluster with the same ISO in Cloudstack 4.17, I can see two services one is bootstrap service & Cloudstack opaque.  In the kubernetes cluster on Cloudstack 4.18, the Cloudstack opaque service was not installed. Maybe this could be the issue, that all services are not getting installed in Cloudstack 4.18. The screenshots are given below for your reference

![4 17 kube](https://github.com/apache/cloudstack/assets/13447
![4 18 kube](https://github.com/apache/cloudstack/assets/134476960/f991670d-cf14-4e23-b410-25c61b2e0356)

6960/d49a8afe-8a60-45d1-a9f1-445b8d414771)

**Comment by kiranchavala** [comment]
Hi @Stanley2911 

Setting up of dashbaord token is not releated to getting up the cluster up and running 

Could you please follow the steps mentioned this article

https://github.com/kubernetes/dashboard/blob/master/docs/user/access-control/creating-sample-user.md

Meanwhile i will cross check internally if cloudstack is generating security token for dashboard

**Comment by weizhouapache** [comment]
This seems to be a valid issue

On CloudStack UI, it mentions
![image](https://github.com/apache/cloudstack/assets/57355700/0948e2f8-0eb5-4c32-b91c-f0b62a4e9087)

However, there is no secrets named `kubernetes-dashboard-token`
![image](https://github.com/apache/cloudstack/assets/57355700/b09cedc1-230c-4b0e-a06c-d33030692778)

Following the instruction link on the page, it works
```
root@k8s-control-1897360043d:~# cat k8s-dash.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: admin-user
  namespace: kubernetes-dashboard
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: admin-user
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
- kind: ServiceAccount
  name: admin-user
  namespace: kubernetes-dashboard

root@k8s-control-1897360043d:~# kubectl apply -f k8s-dash.yaml 
serviceaccount/admin-user created
clusterrolebinding.rbac.authorization.k8s.io/admin-user created

root@k8s-control-1897360043d:~# kubectl -n kubernetes-dashboard create token admin-user
eyJhbGciOiJSUzI1NiIsImtpZCI6IkJqTE9XNDRxYnBaZExfendfMWxNQTgtSUJ6Y0ZlOXJCb2EzTUtfeW5GNXcifQ.eyJhdWQiOlsiaHR0cHM6Ly9rdWJlcm5ldGVzLmRlZmF1bHQuc3ZjLmNsdXN0ZXIubG9jYWwiXSwiZXhwIjoxNjg5OTEzOTY3LCJpYXQiOjE2ODk5MTAzNjcsImlzcyI6Imh0dHBzOi8va3ViZXJuZXRlcy5kZWZhdWx0LnN2Yy5jbHVzdGVyLmxvY2FsIiwia3ViZXJuZXRlcy5pbyI6eyJuYW1lc3BhY2UiOiJrdWJlcm5ldGVzLWRhc2hib2FyZCIsInNlcnZpY2VhY2NvdW50Ijp7Im5hbWUiOiJhZG1pbi11c2VyIiwidWlkIjoiNDc3MTU3MWEtNmU2Mi00ODUyLWJhZWQtZDIzMDZiYjg5MDhiIn19LCJuYmYiOjE2ODk5MTAzNjcsInN1YiI6InN5c3RlbTpzZXJ2aWNlYWNjb3VudDprdWJlcm5ldGVzLWRhc2hib2FyZDphZG1pbi11c2VyIn0.fC9vlpm8vDUpLaWMc6Gk_f7uAAWb3fJDr5DFQbOYu8bungdBkZPLIN50aqgPqoILqrjNQQ2OxEKVrp523cQgJhwFIBnP1Y6k3w5VicZeTnBklOFFfk2ZQ1WtjYL5IozRJZ4pin_L3rnfnorCvR8DpgM39a4bHqXYSuRGS87gK-z9waCOOPRMPMBtOoFz4L9FDvvGSSfpMeNql9ue8EUwdkeY31i7ZvleE2HFHh1V8Z1sQuHGeuEo2xV2GDBAwymx3kG5kCZmLVmO-GgIMMVMSkWMZyOB-9UpxcDdz2iD6BdMH_thp9y_YOKpDbNmYBYUJo74vWFzQ8fxH7RltpUfIg
```

![image](https://github.com/apache/cloudstack/assets/57355700/8b7e2bcf-c4a0-4c15-9184-6343a1fbc406)
