### ISSUE TITLE
Resetting Ubuntu VM Password does not work

### ISSUE THREAD

**Issue by nxsbi** [apache/cloudstack#8767]
##### ISSUE TYPE

 * Other

##### COMPONENT NAME

~~~
UI
~~~

##### CLOUDSTACK VERSION

~~~
4.17.0
~~~

##### CONFIGURATION

NA

##### OS / ENVIRONMENT

Ubuntu 22.04 Server LTS (VM OS)

##### SUMMARY

I want to enable the Change Password functionality for Ubuntu based VM. I have a newly created Ubuntu 22.04 Server Template. I enabled the root user as well, and followed steps in  [https://docs.cloudstack.apache.org/en/latest/adminguide/templates/_password.html](https://docs.cloudstack.apache.org/en/latest/adminguide/templates/_password.html )

However, for Ubuntu I cannot get it to work.  Step 5 is not possible on Ubuntu so tried 
`update-rc.d cloud-set-guest-password defaults`

Even after trying the Change Password from Cloudstack UI, the password does not change and my old password which I used while creating template still works.

These steps worked fine for CentOS, but not working for Ubuntu

##### STEPS TO REPRODUCE

~~~
Create a Ubuntu Template
Follow the cloud-set-guest-password steps - https://docs.cloudstack.apache.org/en/latest/adminguide/templates/_password.html
Create a new VM from this template, - New password that pops up does not work
Chnage password does not work from Cloudstack UI 

~~~

##### EXPECTED RESULTS

~~~
Password works
~~~

##### ACTUAL RESULTS

~~~
Password does not work. 
~~~

**Comment by nxsbi** [comment]
PS - I have also followed the steps in this link 

https://docs.cloudstack.apache.org/en/latest/adminguide/templates/_cloud_init.html#linux-with-cloud-init

Created the files 
- /etc/cloud/cloud.cfg.d/99_cloudstack.cfg
- /etc/cloud/cloud.cfg.d/80_user.cfg

**Comment by kiranchavala** [comment]
@nxsbi 

Have you enabled  the  password option on the template

![Screenshot 2024-03-11 at 12 27 33 PM](https://github.com/apache/cloudstack/assets/1401014/599e223e-87d8-4e0f-8cd5-d5366979554a)

**Comment by kiranchavala** [comment]
@nxsbi 

could you please try with the following configuration 

cat /etc/cloud/cloud.cfg

```
datasource_list: ["CloudStack"]

datasource:
  CloudStack:
    max_wait: 60
    timeout: 30

network:
  config: disabled

users:
  - default

system_info:
  default_user:
    name: root

disable_root: false

ssh_deletekeys: true

cloud_init_modules:
 - seed_random
 - bootcmd
 - write-files
 - growpart
 - resizefs
 - disk_setup
 - mounts
 - set_hostname
 - update_hostname
 - update_etc_hosts
 - ssh
 - users-groups

cloud_config_modules:
 - ssh-import-id
 - locale
 - [ set-passwords, always ]
 - ntp
 - timezone
 - disable-ec2-metadata
 - runcmd

cloud_final_modules:
 - scripts-vendor
 - scripts-per-once
 - scripts-per-boot
 - scripts-per-instance
 - scripts-user
 - puppet

warnings:
  dsid_missing_source: off
```
