### ISSUE TITLE
Host IP address value inconsistent when adding hosts 

### ISSUE THREAD

**Issue by adietrich-ussignal** [apache/cloudstack#8794]
##### ISSUE TYPE

 * Other

##### COMPONENT NAME

~~~
Agent
~~~

##### CLOUDSTACK VERSION

~~~
4.19.0.0
~~~

##### CONFIGURATION

Advanced Networking Setup 

cloudbr0 - Guest/Private VXLAN Bridge 
cloudbr1 - Public Network (VLAN)
cloudbr2 - Management Network (VLAN) 

Three KVM hosts in a single cluster on the same top-of-rack. 

##### OS / ENVIRONMENT

Ubuntu 22.04 LTS 
Below is the netplan configuration from one of the KVM hosts. 
```
---
network:
  version: 2
<Physical and Bond portions omitted for brevity> 
  bridges:
    cloudbr0:
      interfaces:
        - bond0.2007
      addresses:
        - 10.255.0.4/24
      parameters:
        stp: false
        forward-delay: 5
      mtu: 9000
    cloudbr2:
      interfaces:
        - bond0.2003
      addresses:
        - 10.120.0.5/24
      dhcp4: false
      routes:
        - to: default
          via: 10.120.0.1
      nameservers:
        addresses:
          - 10.10.0.10
          - 10.10.0.11
      mtu: 1500
    cloudbr1:
      interfaces:
        - bond0
      parameters:
        stp: false
      mtu: 1500
  vlans:
    bond0.2000:
      id: 2000
      link: bond0
    bond0.2003:
      id: 2003
      link: bond0
      mtu: 1500
    bond0.2007:
      id: 2007
      link: bond0
      mtu: 9000
```
##### SUMMARY

When adding a host to CloudStack, the assigned IP address does not match the IP addressed used to join the host to the cluster. This causes unpredictable results for IP Addresses that are assigned to a host. This breaks a variety of functionality for communications for management and VM traffic.  

##### STEPS TO REPRODUCE

~~~
1. Create the appropriate Advanced Network Configuration settings with a VXLAN capable bridge/VLAN interface with a VTEP IP. 
2. Add host in CloudStack UI with Management bridge IP address. 
~~~

##### EXPECTED RESULTS

~~~
See the management IP address (10.120.0.x) used to add the host reflected in the CloudStack UI. 
~~~

##### ACTUAL RESULTS

~~~
CloudStack reports the 10.255.0.x IP address of the host instead of the host management IP (10.120.0.x) used to add the host to CloudStack. 

In some cases the IP address is added correctly, but it is not persistent and is subject to change in reconnects or agent restarts. 
~~~
