### ISSUE TITLE
cloudstack-agent incorrectly assigning private.network.device

### ISSUE THREAD

**Issue by adietrich-ussignal** [apache/cloudstack#8795]
##### ISSUE TYPE

 * Bug Report

##### COMPONENT NAME

~~~
Agent
~~~

##### CLOUDSTACK VERSION

~~~
4.19.0.0
~~~

##### CONFIGURATION

Advanced Networking

cloudbr0 - Guest/Private (VXLAN)
cloudbr1 - Public Network (VLAN)
cloudbr2 - Management Network (VLAN)

##### OS / ENVIRONMENT

Ubuntu 22.04 LTS 
KVM Hypervisor 

Netplan configuration: 
```
---
network:
  version: 2
  ethernets:
    ens1f0: {}
    ens1f1: {}
    lo:
      match:
        name: lo
      addresses:
        - 10.255.255.12/32
  bonds:
    bond0:
      dhcp4: false
      dhcp6: false
      interfaces:
        - ens1f0
        - ens1f1
      parameters:
        mode: 802.3ad
        mii-monitor-interval: 100
  bridges:
    cloudbr0:
      interfaces:
        - bond0.2007
      addresses:
        - 10.255.0.4/24
      parameters:
        stp: false
        forward-delay: 5
      mtu: 9000
    cloudbr2:
      interfaces:
        - bond0.2003
      addresses:
        - 10.120.0.5/24
      dhcp4: false
      routes:
        - to: default
          via: 10.120.0.1
      nameservers:
        addresses:
          - 10.10.0.10
          - 10.10.0.11
      mtu: 1500
    cloudbr1:
      interfaces:
        - bond0
      parameters:
        stp: false
      mtu: 1500
  vlans:
    bond0.2000:
      id: 2000
      link: bond0
    bond0.2003:
      id: 2003
      link: bond0
      mtu: 1500
    bond0.2007:
      id: 2007
      link: bond0
      mtu: 9000
```

##### SUMMARY

When adding a host to CloudStack, the auto-detected private NIC value is cloudbr2, which does not appear to respect the assigned traffic labels in CloudStack. When attempting to hard-code the values in `agent.properties` the values are not respected and are modified to values that do not correctly reflect the traffic labels. 

##### STEPS TO REPRODUCE

~~~
1. Update agent.properties with a private.network.device=cloudbr0. 
2. Start cloudstack-agent. 
3. Add host in CloudStack UI using the IP address associated with cloudbr2. 
~~~

##### EXPECTED RESULTS

~~~
Host is added successfully to CloudStack. 
~~~

##### ACTUAL RESULTS

~~~
Host does not add and times out with a 530 error. 

Manually updating private.nic.device agent.properties during the host add process can successfully complete the host add. 
~~~
