### ISSUE TITLE
Cannot start instances after adding second host

### ISSUE THREAD

**Issue by Hector-Work** [apache/cloudstack#8810]
##### ISSUE TYPE

 * Other

##### COMPONENT NAME

~~~
Networking
~~~

##### CLOUDSTACK VERSION

~~~
4.19.0.0
~~~

##### CONFIGURATION

Zone created with advanced networking, 1 physical network.

##### OS / ENVIRONMENT

Ubuntu 22.04, KVM

##### SUMMARY

I've had a CloudStack installation working well on a single host for a couple of weeks now. Yesterday I added another host to the cluster. When I went back to look at the instances all of them had stopped. Attempting to start them again resulted in an error. The same happened with the VRs, though the system VMs are fine.

This is the error in the management server logs whenever I try to start an instance:
```
2024-03-20 11:41:20,508 INFO  [c.c.v.VirtualMachineManagerImpl] (Work-Job-Executor-36:ctx-7b172848 job-868/job-869 ctx-6d899296) (logid:698ffc95) Unable to start VM on Host {"id":1,"name":"comp1","type":"Routing","uuid":"2fca77e2-a9d5-4ca3-977f-9fc18e78bd0a"} due to Failed to create vnet 11: Cannot find device "br-11"/usr/share/cloudstack-common/scripts/vm/network/vnet/modifyvlan.sh: line 37: /proc/sys/net/ipv6/conf/br-11.11/disable_ipv6: No such file or directoryCannot find device "br-11.11"Failed to create vlan 11 on pif: br-11.
```

Any help to understand what's going wrong would be much appreciated.

##### STEPS TO REPRODUCE

~~~

~~~

##### EXPECTED RESULTS

~~~
New host is added, and instances continue running.
~~~

##### ACTUAL RESULTS

~~~
Error when attempting to start instances.
~~~

**Comment by weizhouapache** [comment]
@Hector-Work 
it looks like the second host is misconfigured.
please check the network configurations on both hosts

**Comment by Hector-Work** [comment]
Thanks @weizhouapache. Here are the network configs for each host. Host 1 was working fine until I added Host 2, yet the configs are the same.
Host 1:
```
network:
   version: 2
   renderer: NetworkManager
   ethernets:
     enp1s0:
       dhcp4: false
       dhcp6: false
       optional: true
   bridges:
     cloudbr0:
       addresses: [192.168.100.1/24]
       routes:
       - to: default
         via: 192.168.100.254
       nameservers:
         addresses: [1.1.1.1,8.8.8.8]
       interfaces: [enp1s0]
       dhcp4: false
       dhcp6: false
       parameters:
         stp: false
         forward-delay: 0
```
Host 2:
```
network:
   version: 2
   renderer: NetworkManager
   ethernets:
     enp1s0:
       dhcp4: false
       dhcp6: false
       optional: true
   bridges:
     cloudbr0:
       addresses: [192.168.100.1/24]
       routes:
       - to: default
         via: 192.168.100.254
       nameservers:
         addresses: [1.1.1.1,8.8.8.8]
       interfaces: [enp1s0]
       dhcp4: false
       dhcp6: false
       parameters:
         stp: false
         forward-delay: 0
```
