### ISSUE TITLE
Cloud-init not running when guest network use UsedData: ConfigDrive

### ISSUE THREAD

**Issue by leduyquy** [apache/cloudstack#9404]
##### ISSUE TYPE

 * Bug Report

##### COMPONENT NAME

~~~
Cloud-init, Instance 
~~~

##### CLOUDSTACK VERSION

~~~
4.19.0.1
~~~

##### CONFIGURATION

Guest Network type L2 or Isolated set UsedData use ConfigDrive

##### OS / ENVIRONMENT

Ubuntu 22.04 for Managerment Cloudstack
VMware 8

##### SUMMARY

Cloud-init not apply when UsedData use ConfigDrive

##### STEPS TO REPRODUCE

~~~
Create Network L2 or Create isolated network and set UserData use ConfigDrive
Create instance on network
~~~

##### EXPECTED RESULTS

~~~
Cloud-init apply and set user/password, ssh-key, etc
~~~

##### ACTUAL RESULTS

~~~
Cloud-init not apply to instance
~~~

**Comment by shwstppr** [comment]
Hi @leduyquy please refer https://docs.cloudstack.apache.org/en/4.19.0.2/adminguide/virtual_machines.html#using-cloud-init if not already.
Check if the datasource is configured in the template

**Comment by leduyquy** [comment]
I follow this guide bellow:
https://docs.cloudstack.apache.org/en/latest/adminguide/templates/_cloud_init.html

My config:

 /etc/cloud/cloud.cfg.d/99_cloudstack.cfg.

```
datasource_list: [ ConfigDrive, CloudStack, None ]
datasource:
  CloudStack: {}
  None: {}
```

Also I try with bellow:

```
datasource_list: [ ConfigDrive, CloudStack, None ]
datasource:
  ConfigDrive: {}
  None: {}
```

It not working with ConfigDrive. But with VirtualRouter it working normal
